name: ghosts
channels:
  - huggingface
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - yapf=0.31
  - numpy=1.21
  - click=8.0
  - pillow=9.0
  - ninja=1.10
  - pytorch=1.11
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - tensorflow=2.4
  - transformers=4.14
  - pip:
      - aitextgen==0.5.2
      - python-dotenv==0.20.0
      - shortuuid==1.0.8
      - eventlet==0.33.0
      - flask==2.1.2
      - flask-socketio==5.1.2
      - redis==4.3.2
      - walrus==0.9.1
      - climage==0.1.3
      - termcolor==1.1.0
